stages:
  - build
  # - push

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

# before_script:
#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  # only:
  #   - tags
  rules:
    # - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
  tags:
    - omc-gitlab-docker-auto
  before_script:
    - docker info
  script:
    - docker build -t $CI_PROJECT_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} .

# push:
#   stage: push
#   script:
#     - docker push $DOCKER_IMAGE
#   only:
#     - main
#     - master